name: exceptions_flutter
description: Exceptions Flutter is a repository that provides exception in a format
version: 1.0.7+8
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
