name: exceptions_flutter
description: Exceptions Flutter is a repository that provides exception in a format
version: 1.0.5+6
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
